<?php
/**
 * Maho
 *
 * @package    Maho_NetsEasy
 * @copyright  Copyright (c) 2026 Maho (https://mahocommerce.com)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var Maho_NetsEasy_Block_Info $this */
?>
<?= $this->escapeHtml($this->getMethod()->getTitle()) ?>
<?php if ($specificInfo = $this->getSpecificInformation()): ?>
    <table class="netseasy-payment-info">
        <?php foreach ($specificInfo as $label => $value): ?>
            <tr>
                <td><?= $this->escapeHtml($label) ?>:</td>
                <td><?= $this->escapeHtml((string) $value) ?></td>
            </tr>
        <?php endforeach ?>
    </table>
<?php endif ?>
