<?php
/**
 * SPDX-FileCopyrightText: 2026 Maho <https://mahocommerce.com>
 * SPDX-License-Identifier: OSL-3.0
 * @package Maho_NetsEasy
 */

/** @var Maho_NetsEasy_Block_Info $this */
?>
<?= $this->escapeHtml($this->getMethod()->getTitle()) ?>
<?php if ($specificInfo = $this->getSpecificInformation()): ?>
    <table class="netseasy-payment-info">
        <?php foreach ($specificInfo as $label => $value): ?>
            <tr>
                <td><?= $this->escapeHtml($label) ?>:</td>
                <td><?= $this->escapeHtml((string) $value) ?></td>
            </tr>
        <?php endforeach ?>
    </table>
<?php endif ?>
